name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare debug properties
          echo ${{ secrets.DEBUG_STORE_PASSWORD }} >> keystore.properties
          echo ${{ secrets.DEBUG_KEY_ALIAS }} >> keystore.properties
          echo ${{ secrets.DEBUG_KEY_PASSWORD }} >> keystore.properties
