name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare debug keystore.properties
      env:
        DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
        DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
      run: |
          echo ${{secrets.DEBUG_STORE_PASSWORD}} | sed 's/./& /g'
          echo ${{secrets.DEBUG_KEY_ALIAS}} | sed 's/./& /g'
          echo ${{secrets.DEBUG_KEY_PASSWORD}} | sed 's/./& /g'
